### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by xbrunosousa** [talesluna/RastroJS#1]
Boa noite, prezado. 
É possível receber o json como utf-8?

Estou recebendo assim: `"status":"objeto entregue ao destinatï¿½rio"`

Obrigado, e parabéns pela Api! =)

**Comment by talesluna** [comment]
Boa noite, obrigado pelo feedback.

Provavelmente o sistema dos correios mudou o charset de saída.
Vou analisar e assim que resolver aviso aqui.

**Comment by xbrunosousa** [comment]
Valeu pelo retorno, Tales!
Se eu manjasse de back end eu te dava um help aí! rs
Abs

**Comment by gerbesf** [comment]
Eu acho que fiz o pull errado....
uma correção pode ser feita no arquivo:
src/services/correios/correios.findObject.js
adicionando:
encoding: null
ao parametos da requisição

**Comment by talesluna** [comment]
Obrigado @gerbesf 
seu pull request corrigiu o problema, aprovei :+1:
