### ISSUE TITLE
Erro de cors

### ISSUE THREAD

**Issue by leonardotdleal** [talesluna/rastrojs#1]
Boa tarde,

Estou realizando um experimento com a lib e ao realizar a requisição está emitindo erro de CORS.

Preciso corrigir algo no meu front, ou é a API que precisa implementar o CORS?

Obs: fiz a requisição conforme o exemplo.

Att,

**Comment by talesluna** [comment]
Olá @leonardotdleal não há nada de errado com sua aplicação e infelizmente a princípio não há nada que se possa fazer do lado do front-end para essa questão.

Oservidor dos correios está com CORS configurado e bloqueando requisições via browser de origens diferentes e por mais que eu passe o header Sec-Fetch-Mode como "no-cors" tudo que virá é uma resposta "opaque".

Para mais: [https://developer.mozilla.org/pt-PT/docs/Web/Seguranca/politica_de_mesma_origem](https://developer.mozilla.org/pt-PT/docs/Web/Seguranca/politica_de_mesma_origem)

Esta biblioteca nasceu da abstração de uma API (maior que o necessário) que fazia o serviço via back-end onde o CORS não se aplica, você pode criar o seu próprio back-end para este fim (recomendado) ou se preferir pode usar a [rastrojs-api](https://github.com/talesluna/rastrojs-api).

Atualmente eu hospedo essa API no meu heroku, mas não recomendo que aponte produção para lá, serve apenas como demonstração: http://rastrojs.herokuapp.com/
