### ISSUE TITLE
 Unable to resolve module url

### ISSUE THREAD

**Issue by jhsonmac** [talesluna/rastrojs#11]
###  Unable to resolve module url

\projeto\node_modules\rastrojs\dist\rastrojs.js: 
url could not be found within the project or in these directories:
node_modules

Limpei projeto, reinstalei as dependências mas sigo recebendo o erro no modulo  

### Log
![Capturar](https://user-images.githubusercontent.com/38335699/144082518-5ab4511f-951c-4847-9893-07df9802f833.PNG)

**Comment by talesluna** [comment]
Boa tarde @jhsonmac 

O 'url' é um module padrão do Nodejs, não requer instalação adicional e não deveria estar faltando.

Acredito que você esteja tentando utilizar a biblioteca em um projeto front-end (web ou mobile) e caso seja isso infelizmente a rastrojs ainda não é portada para javascript como um todo, atendendo somente NodeJs. Não há planos para essa portabilidade no momento. O uso correto neste caso seria implementar a rastrojs no seu backend, requisitando-o via HTTP pelo seu front.
