### ISSUE TITLE
To lower case

### ISSUE THREAD

**Issue by henrique25teles** [talesluna/rastrojs#2]
Olá! 
Não entendo o porque você fazer o toLowerCase quando está montando o objeto. Não seria melhor deixar do jeito que está e tratar isso na aplicação em uso?

**Comment by talesluna** [comment]
Olá @henrique25teles 

Essa tratativa é para corrigir os dados dos Correios que em alguns casos as informação são publicadas em _upper_ e em outros casos de forma mista (_upper_ e _lower_).
Pra manter o padrão passei tudo para lower após requisição.

Situações que podem ocorrer:

Caso upper
```
SÃO PAULO / SP  - DE UNIDADE DE TRATAMENTO EM SÃO PAULO / SP PARA...
BELO HORIZONTE / MG - OBJETO ENTREGUE AOS DESTINATÁRIO
```

Caso misto
```
Campinas / SP - DE UNICADE DE CAMPISTAS / SP PARA...
SÃO PAULO / SP - De unidade de tratamento em São Paulo / SP para...
BELO HORIZONTE / MG - Objeto entregue ao destinatário
```
Optei por passar para lower justamente por entender que a aplicação que usa (provavelmente front-end) pode fazer a apresentação da forma que achar melhor, com CSS por exemplo
