### ISSUE TITLE
Ajuda com instalação

### ISSUE THREAD

**Issue by flourigh** [talesluna/RastroJS#3]
Olá, eu achei o seu sistema de rastreio extremamente genial, funciona bem no seu heroku de demo
Porém eu faço o que você manda em seu install mas não acontece algo para mim, simplesmente não aparecem as pastas, do env por exemplo, só exibem erros, muitos erros, você poderia me auxiliar?

**Comment by xbrunosousa** [comment]
> Olá, eu achei o seu sistema de rastreio extremamente genial, funciona bem no seu heroku de demo
> Porém eu faço o que você manda em seu install mas não acontece algo para mim, simplesmente não aparecem as pastas, do env por exemplo, só exibem erros, muitos erros, você poderia me auxiliar?

Cá me intrometendo... tá funcionando perfeitamente, cara!
https://youtu.be/OZaaYhMKkTI

**Comment by flourigh** [comment]
opa @xbrunosousa cara, não é intromissão não, você me ajudaria? queria criar um igual ao dele, tipo ter um no heroku e tal mas tudo que faço da erros e não funciona nem local nem heroku, você me ajudaria? realmente não sei como fazer a não ser o que está no readme, e não está funcionando

**Comment by xbrunosousa** [comment]
> @xbrunosousa genial, com o Yarn realmente funcionou, não sei de verdade o que mas quando eu fiz o npm && npm dev não foi, dando os erros, instalei o yarn e funcionou, agora queria fazer um heroku com ele para utilizar

O comando com o npm é `npm i && npm run dev`.
São dois comandos, apenas usei o `&&` para que na finalização do primeiro, rode o segundo...

**Comment by flourigh** [comment]
@xbrunosousa pois é, consegui rodar em heroku local, npm run dev, yarn dev mas em build da muitos erros, erros demais e estou procurando várias soluções e os erros aumentam, eu não consigo fazer rodar no heroku web de forma alguma, primeiro foi nodemon, removi e no local foi mas no web não, depois foi babel e aí mandaram atualizar o babel-cli porém nem sinal de funcionamento que piorou foi tudo até mesmo não rodando no local

**Comment by flourigh** [comment]
é, consegui, nossa, precisou de muitas modificações para funcionar, com muita mas muita busca finalmente consegui, caso a pergunta, para que, medo de o dele não funcionar mais no demo online e ou não sobrecarregar o dele, cara, seu sistema é incrível

**Comment by talesluna** [comment]
Pessoal, desculpem-me a demora, estava viajando e sem notebook.
@flourigh Que bom que @xbrunosousa conseguiu te ajudar e que conseguiu rodar, mas teria como colar aqui os erros que aconteceram no deploy pra eu poder melhorar isso? talvez mais pessoas tenha o mesmo problema.

Abraços.
