### ISSUE TITLE
Receber notificação de atualização.

### ISSUE THREAD

**Issue by lowercase00** [talesluna/rastrojs#5]
Tales, obrigado pela Lib.
Como o Correios disponibiliza atualização push via SMS, me pergunto se há alguma maneira de receber notificação da atualização do status de um pedido. A outra opção seria implementar um worker para fazer a varredura periódica, mas pouco eficiente...
Obrigado!
Abs

**Comment by talesluna** [comment]
Obrigado pela sugestão @lowercase00 

Como está é uma lib apenas, entendo que não cabe implementar qualquer carga de negócio nela, o que pode ser feito é implementar um método na lib que solicita aos correios a inscrição e/ou saída de um número de telefone para determinados objetos, mas caberá à aplicação que utilizar a lib fazer a chamada deste método, enviar notificações, gerir bases de dados etc... Em fim, ser uma aplicação.

Estou colocando a implementação deste método de vinculação do SMS no roadmap da lib, mas fique a vontade para fazer um fork do projeto e enviar pull requests caso queira, qualquer atualização sobre está implementação irei vincular aqui. 

Abraços.
